In [1]:
import numpy as np

In [505]:
# Сигмоида 
def sigmoid(x):
    return 1/(1+np.exp(-x))

def deriv(x):
    return sigmoid(x)*(1-sigmoid(x))
    
# набор входных данных
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# выходные данные            
y = np.array([[0,1,1,0]]).T

# для отладки
np.random.seed(1)

# инициализируем веса случайным образом
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

l0 = X

for i in range(60000):

    l1 = sigmoid(np.dot(l0,syn0))
    l2 = sigmoid(np.dot(l1,syn1))

    # насколько мы ошиблись?
    l2_error = y - l2
    
    if (i % 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))

    l2_delta = l2_error * deriv(l2)
    
    # как сильно значения l1 влияют на ошибки в l2?
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta = l1_error * deriv(l1)

    # обновим веса
    syn1 += l1.T.dot(l2_delta)
    syn0 += np.dot(l0.T,l1_delta)

print("Выходные данные после тренировки:")
print(l2)
print('syn1:\n', syn1)
print('syn0:\n', syn0)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
Error:0.496410031903
Error:0.395889882979
Error:0.028252872986
Error:0.00984912467265
Error:0.00565228621954
Error:0.00375349830674
Выходные данные после тренировки:
[[ 0.00249014]
 [ 0.99689713]
 [ 0.99714958]
 [ 0.00222388]]
syn1:
 [[ 22.98007177]
 [-28.48592703]
 [-63.72727005]
 [-13.26155676]]
syn0:
 [[-91.3033436   -7.93237933 -31.76511626  -1.70096251]
 [-90.21032678 -22.67981393 -64.96982606   0.35429558]
 [ 91.1878002   -1.3617468   -1.36157619   1.18814316]]
